"""
Publish Markdown files to Confluence wiki.

Copyright 2022-2026, Levente Hunyadi

:see: https://github.com/hunyadi/md2conf
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal, NewType

from .clio import boolean_option, composite_option, nullable_option, value_option
from .extension import MarketplaceExtension as MarketplaceExtension
from .extension import MarketplaceExtensionFactory as MarketplaceExtensionFactory
from .options_converter import ConverterOptions
from .options_converter import ImageLayoutOptions as ImageLayoutOptions
from .options_converter import LayoutOptions as LayoutOptions
from .options_converter import TableLayoutOptions as TableLayoutOptions

# Encapsulates a Confluence page ID
ConfluencePageID = NewType("ConfluencePageID", str)

# Encapsulates a snippet of Markdown text
Markdown = NewType("Markdown", str)


@dataclass
class ProcessorOptions:
    """
    Options that control how page content is generated and synchronized.

    :param root_page: Confluence page to assume root page role for publishing a directory of Markdown files.
    :param keep_hierarchy: Whether to maintain source directory structure when exporting to Confluence.
    :param title_prefix: String to prepend to Confluence page title for each published page.
    :param generated_by: Text to use as the generated-by prompt (or `None` to omit a prompt).
    :param overwrite: Whether to overwrite (manual) page changes that occurred since last synchronization.
    :param attachment_sync: Behavior for synchronizing page attachments:
        `full` aligns the Confluence state with the Markdown source as much as possible, removing unreferenced page attachments;
        `upsert` uploads new files and replaces existing attachments with updated files but keeps unreferenced page attachments;
        `create` leaves existing attachments unchanged, even if updated in the source directory.
    :param comments: Behavior for inline comments when page is updated: remove, check if open, or keep.
    :param skip_update: Whether to skip saving Confluence page ID in Markdown files.
    :param keep_state: Whether to keep the Confluence content state (rough draft, in progress, ready for review, verified, etc.) when updating a page.
    :param converter: Options for converting an HTML tree into Confluence Storage Format.
    :param line_numbers: Inject line numbers in Markdown source file to help localize conversion errors.
    :param global_properties: JSON or YAML file of Confluence content properties to merge for every synchronized Markdown file.
    """

    root_page: ConfluencePageID | None = field(
        default=None, metadata=value_option("Confluence page to act as initial parent for creating new pages. Defaults to space home page.")
    )
    keep_hierarchy: bool = field(
        default=False,
        metadata=boolean_option(
            "Maintain source directory structure when exporting to Confluence.",
            "Flatten directories with no `index.md` or `README.md` when exporting to Confluence.",
        ),
    )
    title_prefix: str | None = field(
        default=None,
        metadata=nullable_option(
            "String to prepend to Confluence page title for each published page.",
            "Use Markdown title to synchronize page.",
        ),
    )
    generated_by: Markdown | None = field(
        default=Markdown("This page has been generated with a tool."),
        metadata=nullable_option(
            "Add prompt to pages.",
            "Do not add 'generated by a tool' prompt to pages.",
        ),
    )
    overwrite: bool = field(
        default=True,
        metadata=boolean_option(
            "Overwrite (manual) page changes that occurred since last synchronization.",
            "Skip pages with (manual) changes that occurred since last synchronization.",
        ),
    )
    attachment_sync: Literal["full", "upsert", "create"] = field(
        default="full",
        metadata=value_option("Synchronization mode for Confluence page attachments."),
    )
    comments: Literal["keep", "remove", "check-open"] = field(default="remove", metadata=value_option("Behavior for inline comments when page is updated."))
    skip_update: bool = field(
        default=False,
        metadata=boolean_option(
            "Skip saving Confluence page ID in Markdown files.",
            "Inject published Confluence page ID in Markdown files.",
        ),
    )
    keep_state: bool = field(
        default=False,
        metadata=boolean_option(
            "Keep the Confluence content state (rough draft, in progress, ready for review, verified, etc.) when updating a page.",
            "Clear the Confluence content state when updating a page.",
        ),
    )
    converter: ConverterOptions = field(default_factory=ConverterOptions, metadata=composite_option(flatten=True))
    line_numbers: bool = field(
        default=False,
        metadata=boolean_option(
            "Inject line numbers in Markdown source file to help localize conversion errors.",
            "Leave Markdown source file unmodified.",
        ),
    )
    global_properties: Path | None = field(
        default=None, metadata=value_option("JSON or YAML file of Confluence content properties to merge for every synchronized Markdown file.")
    )


DocumentOptions = ProcessorOptions
